
version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - polish-auto
  commit-message:
    prefix: deps
    include-scope: true
  groups:
    minor-and-patch:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
  ignore:
  - dependency-name: MetaTrader5
    versions:
    - 5.x.x
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - polish-auto
  commit-message:
    prefix: deps
    include-scope: true
  groups:
    actions-minor-and-patch:
      patterns:
      - '*'
      update-types:
      - minor
      - patch

